ARG from
FROM $from

COPY etc/ /etc/
COPY usr/ /usr/

RUN dnf -y copr enable nik012003/nabu-support && \
    mkdir /boot/dtb && \
    rpm-ostree override remove kernel kernel-{core,modules,modules-core} \
        --install linux-sm8150 && \
    dnf -y install \
        xiaomi-nabu-firmware \
        pd-mapper qrtr rmtfs tqftpserv \
        alsa-ucm-conf-xiaomi-nabu \
        qbootctl && \
    systemctl enable rmtfs.service && \
    systemctl enable tqftpserv.service && \
    systemctl enable qbootctl.service && \
    dnf clean all
